git clone https://github.com/atlasgrowth/demandelectric.git
cd demandelectric
npm install
npm run build
git checkout --orphan gh-pages
git reset --hard
git clean -fdx
cp -r dist/* .
git add .
git commit -m "Deploy to GitHub Pages"
git push origin gh-pages --force
